---
- hosts: leaf6a,leaft6b
  connection: local
  gather_facts: no

  tasks:
  - name: "Retrieve Configuration"
    dellos9_command:
      commands: ['show running-config']
    register: show_ver

  - debug: var=show_ver
