---
- hosts: wan15a,wan15b
  connection: local
  gather_facts: no

  tasks:
  - name: "Retrieve Configuration File"
    dellos6_config:
      backup: yes
  #    commands: ['show running-config']
      backup_options:
        dir_path:  /backups/colo
   #     filename: "leaf6a.cfg<current-date>@<current-time>"
   # register: show_ver

  # - debug: var=show_ver
