---
- hosts: leaf6a,leaf6b
  connection: local
  gather_facts: no

  tasks:
  - name: "Retrieve Configuration File"
    dellos9_config:
      backup: true
      commands: ['show running-config']
      backup_options:
         dir_path:  home/ansible/ColoBackup/
   # register: show_ver

  # - debug: var=show_ver
