---
- hosts: leaf6a
  connection: local
  gather_facts: no

  tasks:
  - name: "Retrieve Configuration File"
    dellos9_config:
      backup: yes
  #    commands: ['show running-config']
      backup_options:
        dir_path:  /172.20.16.172/home
   #     filename: "leaf6a.cfg<current-date>@<current-time>"
   # register: show_ver

  # - debug: var=show_ver
