---
- hosts: leaf6a
  connection: local
  gather_facts: no

  tasks:
  - name: "Retrieve Configuration File"
    dellos9_config:
      backup: yes
  #    commands: ['show running-config']
      backup_options:
        dir_path:  /home
   # register: show_ver

  # - debug: var=show_ver
