---
- hosts: leaf6a
  connection: local
  gather_facts: no

  tasks:
  - name: "Get Dell EMC OS9 Show version"
    dellos9_command:
      commands: ['show running-config']
#    register: show_ver

#  - debug: var=show_ver
